#!/usr/bin/env bash

# Update your .ssh/config using linode-ssh-config, first making a copy of the current config
# https://github.com/awilliams/linode-ssh-config

BIN=linode-ssh-config
CONFIG="$HOME/.ssh/config"
CONFIG_BACKUP="$CONFIG.bak"
CONFIG_TEMP="$CONFIG.linode-ssh-config.tmp"

if [ -e $CONFIG ]; then
  if cp $CONFIG $CONFIG.bak ; then 
    echo "Backing up $CONFIG to $CONFIG_BACKUP"
  fi 
fi

if $BIN > $CONFIG_TEMP && mv $CONFIG_TEMP $CONFIG; then
  echo "Updated $CONFIG"
fi
